# -*- coding: utf-8 -*-
"""DAY1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkhDYKqIBBQaYe9N19AOq8zYJyi4gXaE
"""

print("hello,world")
print("lavanya")
print("computer science and engineering")

print("i am your student")

print("hkheiewhshdguwiwokjdk")""

prin("i am your teacher")

print("hjiwsgh")
"""hbth""

x=10
print(x)
y=3.14
print(y,name)
name="john"
print(name)
print(name,"is a teacher")
print(x,y,name)

name=input("enter student name")
a=input("enter a number")
print(name)

a=int(input("enter a number"))
b=int(input("enter a number"))
print(a+b)
print(a*b)
print(a/b)
print(a-b)
print(a%b)
print(a**b)

celsius=float(input("enter temperature in class:"))
fahrenheit=(celsius*9/5)+32
print("temperature in fahrenheit:,fahrenheit")



radius=float(input("enter the radius"))
pi=3.14
area=pi*radius**2
print("area of circle is:",area)